### ISSUE TITLE
Broken link on ash-hq

### ISSUE THREAD

**Issue by totaltrash** [team-alembic/ash_authentication#139]
I'm going through the doco today setting up ash_authentication on a play app, I've noticed a couple of broken links and oddities on ash-hq, so will add to the list as I go:

---

This link doesn't work for me in ash-hq on the [getting started](https://ash-hq.org/docs/guides/ash_authentication/latest/tutorials/getting-started-with-authentication#choosing-your-extensions--strategies-and-add-ons) page (page has no content and appears to crash liveview?) but it does work on hexdocs:

![image](https://user-images.githubusercontent.com/637350/212783194-3184f298-41b7-48cb-bdc7-ea7703284b6a.png)

Could be a ash-hq thing?

---

I've got the same issue with the 'Using with Phoenix' link in the summary:

![image](https://user-images.githubusercontent.com/637350/212784963-285d85e1-9ab9-4a17-b4b6-77a1f62c93cc.png)

---

And the same with the 'Getting started with Ash Authentication' link on the [integrating with phoenix page](https://ash-hq.org/docs/guides/ash_authentication/latest/integrating-ash-authentication-and-phoenix):

![image](https://user-images.githubusercontent.com/637350/212789077-37148c79-5e82-4f90-a406-5c8030f40e7c.png)

---

Unformed links are showing on the [integrating with phoenix page](https://ash-hq.org/docs/guides/ash_authentication/latest/integrating-ash-authentication-and-phoenix):

![image](https://user-images.githubusercontent.com/637350/212788365-e30093ef-8da6-494c-8e13-56399b868026.png)

---

**Comment by zachdaniel** [comment]
@jimsynz I'll handle these.

**Comment by kernel-io** [comment]
typo here (revocationr)
https://github.com/team-alembic/ash_authentication/blob/main/lib/ash_authentication/token_resource.ex#L197

also trying to remember where I saw a code example that had a `do` as a closing block instead of `end`

**Comment by totaltrash** [comment]
ah, good one, the tokens section on the user resource
