### ISSUE TITLE
Feature Request for `magic_link` strategy

### ISSUE THREAD

**Issue by wintermeyer** [team-alembic/ash_authentication#155]
I would love to use Ash for the next version of https://www.vutuv.de (a social network Phoenix application). We don't store any passwords but send a `magic_link` by email or a PIN code by SMS.  It would be great if `ash_authentication` would support sending a `magic_link`. Thank you for the great work!

**Comment by jimsynz** [comment]
@wintermeyer thanks for the request. I'll take a look at supporting it and report back.

**Comment by jimsynz** [comment]
Closed by #184
