### ISSUE TITLE
Documentation 404 and errors

### ISSUE THREAD

**Issue by absowoot** [team-alembic/ash_authentication#266]
I'm working through the Ash Authentication tutorials and keep seeing references to [AshAuthentication.Secret](http://ash-hq.org/docs/module/ash_authentication/latest/ashauthentication-secret) which results in a 404.

Additionally, the [examples found here](https://ash-hq.org/docs/module/ash_authentication/latest/ashauthentication-strategy-oauth2) seem to be missing an `end` on the last line.

**Comment by sevenseacat** [comment]
It looks like the issue around AshAuthentication.Secret has been resolved when all of the docs were moved to hexdocs - the references to the module in the "examples found here" link correctly link through to the right module.

And I'll fix those missing `end`s in the examples :)
