### ISSUE TITLE
Primary key not counted as identity for magic link

### ISSUE THREAD

**Issue by skanderm** [team-alembic/ash_authentication#332]
Primary keys aren't currently being counted as an identity for magic_link creation. I've gotten around it by adding the primary key as an identity, which creates an extra unique index on it:

```elixir
identities do
  identity :id, [:id]
end
```

My use case was that I wanted a single-click unsubscribe link for a Subscription resource that used the magic_link functionality (which works great!).

**Comment by jimsynz** [comment]
Thanks for the report!
