### ISSUE TITLE
Support custom strategies that may do things like access a database or read external configuration

### ISSUE THREAD

**Issue by zachdaniel** [team-alembic/ash_authentication#34]
An idea I'm writing down for posterity, and to help us avoid locking ourselves out of this in the future: 

In order to support a "bring your own SSO" feature set (i.e people using Ash have customers who want to use their own SSO), we will want to support something like this:

```elixir
strategies do
  custom :bring_your_own_sso, BringYourOwnSSO
end
```

and then we get a strategy struct by calling `BringYourOwnSSO.strategy(conn)` (or something like that).

Additionally, it might honestly be easier to just support this intrinsically in the framework, i.e have them create a resource and use a `DynamicOauthProvider` extension, and then they could hook it in like so:

```elixir
strategies do
  dynamic :dynamic_sso, MyApp.Resources.DynamicOauthProvider
end
```

And then we can provide actions and components and what-not for managing instances of these dynamic oauth configurations.

**Comment by jimsynz** [comment]
I think you'll be pleasantly surprised by how easy this will be to do.
