### ISSUE TITLE
Distinguish between "no user found" and "cannot contact the DB"

### ISSUE THREAD

**Issue by sevenseacat** [team-alembic/ash_authentication#370]
We had a case recently where the DB host in our app went down, but the homepage of our app continued to render, despite performing database queries relating to showing current-user-specific information.

AshAuthentication swallows errors relating to database connectivity under a "user not found", as part of looking up the user that a JWT belongs to - https://github.com/team-alembic/ash_authentication/blob/main/lib/ash_authentication.ex#L221-L234 - and also as part of sign in (but I'm not sure where that happens).

So in our case, the web app behaved as if no-one was logged in (even when they were), but would not allow sign-in (because DB connection errors there were also being swallowed?) which wasn't an optimal scenario!

**Comment by jimsynz** [comment]
Yeah, I think what we should do is special case database errors and (re)raise them.

**Comment by jimsynz** [comment]
Having thought a little more about this I think that we shouldn't surface this to the app - regardless of _why_ the user can't be verified they still can't be verified.  It feels to me like this is something that should be the responsibility of a health check.
