### ISSUE TITLE
Error after updating from ash_authentication 3.11.8 => 3.11.15

### ISSUE THREAD

**Issue by koenusz** [team-alembic/ash_authentication#436]
I have an application with ash_authentication and ash_authentication_phoenix.

I got the following error after I wanted to go to the sign-in page:
<details>
<summary>error log</summary>
[info] GET /sign-in
[debug] Processing with AshAuthentication.Phoenix.SignInLive.sign_in/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 19ms
[error] #PID<0.645.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.615.0>, stream id 6) terminated
Server: localhost:4000 (http)
Request: GET /sign-in
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for %AshAuthentication.Strategy.Password.Resettable{token_lifetime: {3, :days}, request_password_reset_action_name: :request_password_reset_with_password, password_reset_action_name: :password_reset_with_password, sender: {Genai.Accounts.User.Senders.SendPasswordResetEmail, []}} of type AshAuthentication.Strategy.Password.Resettable (a struct). This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Stream, StreamData
        (elixir 1.15.4) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.15.4) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.15.4) lib/enum.ex:409: Enum.any?/1
        (ash_authentication_phoenix 1.7.3) lib/ash_authentication_phoenix/components/password.ex:110: AshAuthentication.Phoenix.Components.Password."render (overridable 1)"/1
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/utils.ex:229: Phoenix.LiveView.Utils.to_rendered/2
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:330: Phoenix.LiveView.Diff.component_to_rendered/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:705: Phoenix.LiveView.Diff.render_component/9
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:657: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:629: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/static.ex:252: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (genai 0.1.0) lib/genai_web/endpoint.ex:1: GenaiWeb.Endpoint.plug_builder_call/2
        (genai 0.1.0) deps/plug/lib/plug/debugger.ex:136: GenaiWeb.Endpoint."call (overridable 3)"/2
        (genai 0.1.0) lib/genai_web/endpoint.ex:1: GenaiWeb.Endpoint.call/2
        (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4

</details>

![image](https://github.com/team-alembic/ash_authentication/assets/5352759/8d79c963-a7a2-4ee8-9334-68f162206295)

**Comment by zachdaniel** [comment]
👋 please update `ash_authentication_phoenix` as well. This was a buggy release that has since been fixed.

**Comment by koenusz** [comment]
Great, will have another go.
