### ISSUE TITLE
Setup guide note for bcrypt_elixir's default log_rounds in test env

### ISSUE THREAD

**Issue by brady131313** [team-alembic/ash_authentication#476]
There should be a note in the getting started guide about setting bcrypt_elixir's log_rounds to 1 in test environment otherwise tests using a register action will be much slower.

```elixir
config :bcrypt_elixir, :log_rounds, 1
```

**Comment by jimsynz** [comment]
Suggestions on _where_ in the docs this should go?

**Comment by jimsynz** [comment]
I think it should be in the getting started guide and in the moduledocs of `AshAuthentication.Strategy.Password`.

**Comment by sevenseacat** [comment]
I don't think Getting Started is the best place for it (it's literally only the basics of how to get up and running) - if we had a dedicated testing guide it'd make perfect sense to put it there, but we don't.

Ah maybe I'll add one and see what I can put in there...
