### ISSUE TITLE
`get_by_subject` action is configured as `get? true` but does not have any arguments or filters

### ISSUE THREAD

**Issue by zachdaniel** [team-alembic/ash_authentication#486]
The `get_by_subject` action currently requires that you filter by primary key when running the action. Technically the action just "reads whatever". This is not a security issue, but the issue becomes apparent when exposing the action in `ash_admin`, because it accepts no inputs and therefore fails because too many entries would be returned. The action should either take specific arguments and/or we should just require that a primary read action exists and use that instead of our own `get_by_subject` action.

**Comment by jimsynz** [comment]
Can you tell that it was the first time I had ever used a read action? lol.  I don't think it would be a breaking change to make it actually take the argument and work correctly as it's always called via `AshAuthentication.subject_to_user/2..3` anyway.
