### ISSUE TITLE
Consider providing an `AshGraphql.Error` impl for `AshAuthentication.Errors.AuthenticationFailed`.

### ISSUE THREAD

**Issue by zorn** [team-alembic/ash_authentication#498]
For my own project that is using `AshAuthentication` and exposing the `sign_in_with_password` function to the GraphQL API, I've added this implementation so that AshGraphQL can convert the error response to something suitable for public consumption.

This project might consider providing a similar default implementation.

```elixir
# lib/study_hall/ash_graphql_error_impl/authentication_failed.ex
defimpl AshGraphql.Error, for: AshAuthentication.Errors.AuthenticationFailed do
  @moduledoc """
  Provides an implementation of `AshGraphql.Error` protocol for authentication errors
  that come out of the `AshAuthentication` library.

  You can find other implementations here:
  https://github.com/ash-project/ash_graphql/blob/main/lib/error.ex
  """

  def to_error(error) do
    # The `AuthenticationFailed` actually has detailed information about the
    # error, like `Password is not valid` or `query returned no users` but we do
    # not want to leak those details over the API, so we'll return a static
    # error message.
    %{
      message: "could not sign in with the provided credentials",
      shortMessage: "could not sign in with the provided credentials",
      vars: Map.new(error.vars),
      code: Ash.ErrorKind.code(error),
      fields: List.wrap(error.field)
    }
  end
end

```

**Comment by zorn** [comment]
I used the key `shortMessage` because when I did tried `short_message`, my observation was that it was not getting camel-cased in the graph response, but I might have missed something.

**Comment by jimsynz** [comment]
The main issue is that it's not apparent to me which codebase this should go in?

**Comment by zorn** [comment]
> The main issue is that it's not apparent to me which codebase this should go in?

Yeah, I understand that confusion.

After some consideration, I don't think it's helpful to couple error concerns across two distinct ash projects. Neither should really assume the other's presence if at all possible. 

Some coupling is hard to avoid, but this one is pretty easy to say no to IMO.

In the future (if other needs are discovered) I could maybe see a new project like `ash_authentication_graphql` popup to help gel the two projects gel better (like `phoenix_ecto`) but for now, closing the issue/suggestion.

**Comment by jimsynz** [comment]
I think it might be worth putting this in a guide or something? Do you feel like taking a swing at a graphql guide for AshAuthentication?

**Comment by zorn** [comment]
> I think it might be worth putting this in a guide or something? Do you feel like taking a swing at a graphql guide for AshAuthentication?

I'm considering trying to give back to the docs once I get my API endpoint in a good place and feel like I know what's going on. :)
