### ISSUE TITLE
Allow setting custom error messages when authentication fails

### ISSUE THREAD

**Issue by Awlexus** [team-alembic/ash_authentication#507]
I have not been able to find a place where you could custom error messages, if the authorization was unsuccessful. For example, when using the password-strategy, you get the following error-cause when you enter an invalid password: 
```elixir
{:error,
 %Ash.Error.Forbidden{
   errors: [
     %AshAuthentication.Errors.AuthenticationFailed{
       field: nil,
       strategy: %AshAuthentication.Strategy.Password{
         # ...
       },
       caused_by: %{
         message: "Password is not valid" # This error over here
       }
     }
   ]
 }
}
```

I see 2 potential problems with this: 
1. (Localization) You cannot translate errors, unless you try to do it dynamically.
2. (Security) You cannot prevent enumeration attacks.

I'm not sure what would be the ideal approach to implement custom error messages. My initial, naive idea would be to add them to the DSL and allow for the following arguments `String.t() | {module(), atom()} | (map()) -> String.t())` as arguments.`map()` would be possible bindings. Thanks for any feedback

**Comment by zachdaniel** [comment]
first thing to note: I think that error is specifically when the password is not a valid password, not when the username/password combination is wrong. We handle that in such a way that you can't simply try email/password combos and see what works. However, if you have a valid email you could the enumerate. There are discussions elsewhere IIRC about building in ways to prevent this, which I am for.

We have a concept of an "error_handler" which can intercept errors and return new errors instead. `ash_authentication` could potentially allow you to supply one to use for the generated sign in with password action.

**Comment by Awlexus** [comment]
> I think that error is specifically when the password is not a valid password

OK, I tested it again, and now it really does give a different error message now. Which makes me wonder how I was able to trigger it in the first place. I created a user with password "testtest" and to check the error message I thought I'd just hit "t" a couple more times, so the password I entered to trigger it should have been something like "testtesttttt". Not sure how that could become an invalid password.

I didn't know about the concept of "error_handler" where could I read up on those? As a side note, currently trying to search for "error" or "error_handler" on ash-hq.org causes the live view to crash, so I'm not really sure where to find it in the documentation 😅

**Comment by jimsynz** [comment]
The `caused_by` of the error should never be shared with a user.  We use it for logging when `config :ash_authentication, debug_authentication_failures?: true` - which should only ever be done in your dev environment.

Given that you have handle how both successful and failed authentications happen [in your auth plug](https://hexdocs.pm/ash_authentication/AshAuthentication.Plug.html) you can provide any kind of feedback to the user that you want.

I would be open to a separate issue on [AAP](https://github.com/team-alembic/ash_authentication_phoenix/) to enable translations for the UI, etc.
