### ISSUE TITLE
Optionality of Token (in Getting Started guide)

### ISSUE THREAD

**Issue by benswift** [team-alembic/ash_authentication#671]
_posted originally on [elixirforum](https://elixirforum.com/t/ash-authentication-optionality-of-token/63340), but it was suggested I create an issue as well._

The Ash authentication [getting started guide ](https://hexdocs.pm/ash_authentication/4.0.0-rc.6/getting-started-with-authentication.html#example) indicates (in the example setup code) that the `Token` is optional:

> You can skip this step if you don’t want to use tokens, in which case remove the `tokens` DSL section in the user resource below.

However, I tried to follow the “tokens optional” instructions, but couldn’t get past this Spark DSL error:

```
ben@_ my_app % mix compile
Compiling 28 files (.ex)
** (EXIT from #PID<0.98.0>) an exception was raised:
    ** (WithClauseError) no with clause matching: :error
        (ash_authentication 4.0.0-rc.6) lib/ash_authentication/verifier.ex:51: anonymous fn/1 in AshAuthentication.Verifier.validate_token_resource/1
        lib/my_app/accounts/user.ex:1: anonymous fn/1 in MyApp.Accounts.User.__verify_spark_dsl__/1
        (elixir 1.16.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        lib/my_app/accounts/user.ex:1: MyApp.Accounts.User.__verify_spark_dsl__/1
        (elixir 1.16.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir 1.16.2) lib/module/parallel_checker.ex:271: Module.ParallelChecker.check_module/3
        (elixir 1.16.2) lib/module/parallel_checker.ex:82: anonymous fn/6 in Module.ParallelChecker.spawn/4
```

After adding the Token stuff it compiled fine.

Is the `Token` stuff *actually* optional and I just did it wrong (can send more code if it’s helpful, but I just copy-pasted the example code from the docs)? If not, it might be worth updating the docs.

## my setup

fwiw, I’m on the very bleeding edge for everything (ash 3.0.0-rc.45, ash_authentication 4.0.0-rc.6) and I’m also using AshSqlite instead of AshPostgres. So I’m off the beaten path a bit, but still doing things that the docs seem to suggest should be supported.

Anyway, I’m not blocked but wanted to raise the issue in case the docs need tweaking, since I know that that’s part of the focus for Ash v3.

**Comment by zachdaniel** [comment]
Might be worth it to upgrade your `ash_sqlite` dependency, there was a recent fix there. *probably* not relevant, but can't hurt :)

**Comment by benswift** [comment]
Ok, will try that.

**Comment by zachdaniel** [comment]
Based on this comment, this has been completed :) https://elixirforum.com/t/ash-authentication-optionality-of-token/63340/8?u=zachdaniel
