### ISSUE TITLE
'Get Started' tutorial issue: `undefined function policies/1 (there is no such import)`

### ISSUE THREAD

**Issue by arcanemachine** [team-alembic/ash_authentication#682]
OS: Ubuntu 23.04
Erlang version: 26.2.5
Elixir version: 1.16.2-otp-26

Ash deps:

```
      {:ash, "~> 3.0"},
      {:ash_authentication, "~> 4.0"},
      {:ash_postgres, "~> 2.0"},
      {:picosat_elixir, "~> 0.2"}
```

---

The 'Get Started' section contains this code snippet:

```elixir
# lib/my_app/accounts/token.ex

defmodule MyApp.Accounts.Token do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAuthentication.TokenResource],
    domain: MyApp.Accounts

  postgres do
    table "tokens"
    repo MyApp.Repo
  end

  # If using policies, add the following bypass:
  # policies do
  #   bypass AshAuthentication.Checks.AshAuthenticationInteraction do
  #     authorize_if always()
  #   end
  # end
end
```

If the commented-out section at the bottom is un-commented, the following error appears when attempting to start an IEx session for the application:

```
$ iex -S mix
Compiling 1 file (.ex)
    error: undefined function policies/1 (there is no such import)
    │
 12 │   policies do
    │   ^
    │
    └─ lib/helpdesk/accounts/token.ex:12:3: Helpdesk.Accounts.Token (module)


== Compilation error in file lib/helpdesk/accounts/token.ex ==
** (CompileError) lib/helpdesk/accounts/token.ex: cannot compile module Helpdesk.Accounts.Token (errors have been logged)
```

As a side issue, it is not clear what the purpose of this code is. The comment says to add it if you are using policies, but as a newcomer, I am not sure if I am (although the `User` module does define a `policies` section, I assume that means I am using policies[?). For now, the entire snippet (comment and all) just adds confusion.
 
Thanks!

EDIT: These same snippets are present in the AshAuthenticationPhoenix 'Get Started' docs as well, so any changes should be made there as well.

**Comment by zachdaniel** [comment]
Ah, right, we need to add `authorizers: [Ash.Policy.Authorizer]`. I imagine we should add that to the comment to make it clearer? Would you like to PR that change?

**Comment by arcanemachine** [comment]
I can do that. I'll need <= 24 hours before I can get to it, so no hard feelings if anyone is able to get it done before me.

**Comment by zachdaniel** [comment]
Thanks! Looks great 🥳
