### ISSUE TITLE
Token section has to have "enabled? true"

### ISSUE THREAD

**Issue by omanuke** [team-alembic/ash_authentication#703]
https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/get-started
lib/example/accounts/resources/user.ex
<img width="424" alt="image" src="https://github.com/team-alembic/ash_authentication/assets/1901757/f1c2f4c1-48f1-4a38-8534-5dbf57c87662">

**Comment by omanuke** [comment]
There are a lot of places to fix same one like https://github.com/team-alembic/ash_authentication/issues/679 ?

**Comment by zachdaniel** [comment]
These docs will be updated on the next version that is released. It is fixed in main, but AshHq only updates on new version releases.
