### ISSUE TITLE
 ash_apis ramains.

### ISSUE THREAD

**Issue by omanuke** [team-alembic/ash_authentication#704]
https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/get-started
In Add to Config section,
<img width="326" alt="image" src="https://github.com/team-alembic/ash_authentication/assets/1901757/d2688af6-26de-42e5-b7d9-80247a45c7be">

**Comment by zachdaniel** [comment]
This has been updated in `main`, but not yet had a deploy. It will be updated on next deploy. Thanks for the report :)
