### ISSUE TITLE
After creating an account via magic link, email address must be confirmed before another magic link can be used

### ISSUE THREAD

**Issue by sevenseacat** [team-alembic/ash_authentication#843]
ie.

* Register new account via magic link
* Click magic link in email
* I am now signed in
* I get an email confirmation email (!)
* I sign out
* I try to sign in with another magic link
* I can't, because my account is unconfirmed. (!)

This feels like a bit of an edge case but something I just noticed.

If we're creating an account via a magic link, should that count as confirmation? So we don't have to send another confirmation, and can auto-confirm the user.

**Comment by zachdaniel** [comment]
Right, so this is really just a misconfiguration made by the generators. We have an `auto_confirm_actions` list, and the magic link sign in action should be in that list.
