### ISSUE TITLE
Field Policies for Current User are not working with AshAuthentication.Checks.AshAuthenticationInteraction

### ISSUE THREAD

**Issue by allenwyma** [team-alembic/ash_authentication#849]
I currently am applying a field policy so users cannot see other users email address, but the current_user seems to not allow me to bypass this policy:

```elixir
field_policies do
    field_policy_bypass :* do
      authorize_if AshAuthentication.Checks.AshAuthenticationInteraction
      authorize_if actor_attribute_equals(:admin, true)
    end

    field_policy [:email] do
      authorize_if expr(id == ^actor(:id))
      authorize_if relates_to_actor_via(:contacts)
    end

    field_policy :* do
      authorize_if actor_present()
    end
  end
```

Upon further investigation, the `AshAuthentication.Checks.AshAuthenticationInteraction` is looking for `subject: %{context: %{private: %{ash_authentication?: true}}}}, ` in the second argument, but this argument has the subject with the value of `nil`.

**Comment by zachdaniel** [comment]
Fixed in https://github.com/ash-project/ash/commit/a3a6bdff1e252c47423e61107d0ccfc5ff895d63
