### ISSUE TITLE
improve generated password reset actions

### ISSUE THREAD

**Issue by dogezen** [team-alembic/ash_authentication#854]
when adding ash_authentication with the password strategy, the following actions are being created:

`password_reset_with_password` -> which takes in the reset token, a new password and the password confirmation

`request_password_reset_with_password` -> which takes in the email and sends out an email with the reset token url

Ideally, the `password_reset_with_password` would be the action that takes in the existing password and a new password (with confirmation) to replace the existing password.

and we'd also have a `reset_password_with_token` or `password_reset_with_token` action would be the one that, as with now, accepts the reset token, new password and new password confirmation

**Comment by dogezen** [comment]
Steps to reproduce:

```bash
# create project
mix igniter.new auth_demo --install ash,ash_postgres,ash_phoenix,ash_authentication,ash_authentication_phoenix --with phx.new

# add password strategy
mix ash_authentication.add_strategy password  
```

**Comment by zachdaniel** [comment]
Fixed in `main`. We now apply better names for the actions, and add a `change_password` action in the generators.
